[package]
name = "meowland"
version = "0.1.0"
edition = "2024"

license = "MIT"
publish = false

[dependencies]
base64 = "0.23.1"
calloop = "0.14.5"
postcard = { version = "1.1.3", default-features = false, features = [
  "use-std",
] }
crossterm = { git = "https://github.com/crossterm-rs/crossterm.git", default-features = false, features = [
  "bracketed-paste",
  "events",
] }
flate2 = "1.1.10"
libloading = "0.9.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_bytes = "0.11.19"
signal-hook = "0.4"
thiserror = "2.0.21"
tracing = "0.1"
tracing-journald = "0.3.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rustix = { version = "1.1.5", features = [
  "event",
  "fs",
  "net",
  "pipe",
  "process",
  "runtime",
  "shm",
  "stdio",
  "termios",
] }
smithay = { git = "https://github.com/Smithay/smithay.git", default-features = false, features = [
  "wayland_frontend",
  "desktop",
  "backend_drm",
  "renderer_gl",
] }
wl-clipboard-rs = "0.9.4"
usage-rs = { version = "7.0.0", default-features = false, features = [
  "completions",
  "diagnostics",
  "help",
] }

[dev-dependencies]
criterion = { version = "0.8.2", default-features = false, features = [
  "cargo_bench_support",
] }
[[bench]]
name = "kitty"
harness = false

[[bench]]
name = "protocol"
harness = false

[lints]
[lints.rust]
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
unsafe_code = "deny"

[lints.clippy]
cast_possible_wrap = "allow"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"

nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
