name: ci

on:
  - push
  - pull_request

permissions:
  actions: write
  contents: read

jobs:
  check:
    name: check

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: install libraries
        run: sudo apt-get update && sudo apt-get install --yes libxkbcommon-dev pkg-config

      - name: install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: check code
        run: cargo clippy --all-targets --all-features -- -D warnings

  check-nix:
    name: check nix

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup nix
        uses: ./.github/actions/setup-nix

      - name: check flake
        run: nix flake check

  build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup nix
        uses: ./.github/actions/setup-nix

      - name: build the compositor
        run: nix build .#default

      - name: smoke test the binary
        run: ./result/bin/meowland --help
